version: "3.8"
services:
  first-docker-container:
    build: .
    ports:
      - "3000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env